import { Geist, Geist_Mono } from "next/font/google";
import { Markazi_Text, VT323 } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const vt323 = VT323({
  subsets: ['latin'],
  weight: "400",
  variable: '--font-vt323',  
});

const markazi = Markazi_Text({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-markazi',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${markazi.variable} ${vt323.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
